### ISSUE TITLE
Palette colors are not unique

### ISSUE THREAD

**Issue by AlfredJKwack** [briangonzalez/rgbaster.js#12]
Hi,

I've noticed that the color palette contains the same color several times.
Is this a bug or a 'feature'?

https://jsfiddle.net/a1gvy1ru/3/

**Comment by buffcode** [comment]
I think the logic in [this line](/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L96) is not correct.
Since the palette is of fixed size (via `opts`, defaults to `10` elements) this code is supposed to drop a single color off the palette, if it has a lower count.
But this undermines the de-duplication logic in the code before ([line 82ff](/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L82)), as a color may already exist within the palette.

I propose that we remove the palette logic at this point. At the end of the process we sort the variable `colorCounts` and return the `1..<paletteSize>` items (thus dropping the dominant color).

**Comment by AlfredJKwack** [comment]
I think I understand what you're saying. Here's what I think may be going on.

Lets assume:
- An image with 11 pixels. 
- The second and last pixels have the same color. 
- The palette size is set to 10
- We've iterated over the first 10 pixels in the data stream and we're at the 11th color.

At this point, all 10 palette positions are filled with a color. When the.some method is triggered on [line 96](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L96) it will replace the color in the first index position of the palette since the current colorCount = 2 and that's more than whatever is in the first index position. So now we have the same color in the first and second index of the palette.

Did I get it right?

**Comment by buffcode** [comment]
Yes I think that's what is going on.

Additionally we always have a fixed size of palette colors, even if there aren't that many colors (unlikely but possible). For example checking against a pure black/white image should return a palette size with a maximum of 2 colors, regardless of the `paletteSize` value.

**Comment by AlfredJKwack** [comment]
I agree that it would probably be simpler to perform a sort on an truncate at the end.

**Comment by buffcode** [comment]
@briangonzalez Accepting PRs for this solution? I would contribute the patch.

**Comment by AlfredJKwack** [comment]
Thanks for accepting the PR!
Closing.
